# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])


# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print('shape :',a1.shape)
print('ndim :',a1.ndim)
print('type :',a1.dtype)
print('size :',a1.size)

shape : (3,)
ndim : 1
type : int32
size : 3


In [5]:
# Attributes of 2-dimensional array
print('shape :',a2.shape)
print('ndim :',a2.ndim)
print('type :',a2.dtype)
print('size :',a2.size)

shape : (2, 3)
ndim : 2
type : int32
size : 6


In [8]:
# Attributes of 3-dimensional array
print('shape :',a3.shape)
print('ndim :',a3.ndim)
print('type :',a3.dtype)
print('size :',a3.size)

shape : (1, 2, 3)
ndim : 3
type : int32
size : 6


In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame(a2)
data

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros((7,2,3))
print(zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [18]:
# Create an array within a range of 0 and 100 with step 3
step = np.arange(0,100,3)
print(step)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
c = np.random.randint(0,10,(7,2))
print(c)

[[1 2]
 [2 6]
 [6 8]
 [7 4]
 [0 2]
 [9 8]
 [2 5]]


In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
d = np.random.rand(3,5)
print(d)

[[0.74410949 0.60431131 0.52600472 0.55460532 0.29383494]
 [0.15910958 0.94412454 0.20403376 0.38087073 0.86239517]
 [0.74037923 0.49279519 0.84643364 0.43674206 0.28752438]]


In [27]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
e = np.random.randint(0,10,(4,6))
print(e)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [34]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var = np.random.randint(1,10,(3,7))
print(var)
# Find the unique numbers in the array you just created
np.unique(var)

[[1 4 7 2 3 1 5]
 [1 8 1 1 2 2 6]
 [7 5 1 1 3 2 5]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
# Find the 0'th index of the latest array you created
var[0]

array([1, 4, 7, 2, 3, 1, 5])

In [36]:
# Get the first 2 rows of latest array you created
var[:2]

array([[1, 4, 7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2, 2, 6]])

In [37]:
# Get the first 2 values of the first 2 rows of the latest array
var[:2,:2]

array([[1, 4],
       [1, 8]])

In [43]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a = np.random.randint(0,10, (3,5))
ones = np.ones_like(a)
a

array([[0, 4, 4, 6, 8],
       [8, 2, 2, 2, 3],
       [7, 5, 7, 0, 7]])

In [44]:
# Add the two arrays together
a + ones

array([[1, 5, 5, 7, 9],
       [9, 3, 3, 3, 4],
       [8, 6, 8, 1, 8]])

In [45]:
# Create another array of ones of shape (5, 3)
onest = ones.T
onest

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
# Try add the array of ones and the other most recent array together
ones + onest

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [47]:
# Create another array of ones of shape (3, 5)
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
# Subtract the new array of ones from the other most recent array
ones - a

array([[ 1, -3, -3, -5, -7],
       [-7, -1, -1, -1, -2],
       [-6, -4, -6,  1, -6]])

In [54]:
# Multiply the ones array with the latest array
ones * a

array([[0, 4, 4, 6, 8],
       [8, 2, 2, 2, 3],
       [7, 5, 7, 0, 7]])

In [55]:
# Take the latest array to the power of 2 using '**'
a**2

array([[ 0, 16, 16, 36, 64],
       [64,  4,  4,  4,  9],
       [49, 25, 49,  0, 49]])

In [56]:
# Do the same thing with np.square()
np.square(a)

array([[ 0, 16, 16, 36, 64],
       [64,  4,  4,  4,  9],
       [49, 25, 49,  0, 49]])

In [60]:
# Find the mean of the latest array using np.mean()
np.mean(a)

4.333333333333333

In [61]:
# Find the maximum of the latest array using np.max()
np.max(a)

8

In [62]:
# Find the minimum of the latest array using np.min()
np.min(a)

0

In [63]:
# Find the standard deviation of the latest array
np.std(a)

2.6749870196985173

In [64]:
# Find the variance of the latest array
np.var(a)


7.155555555555555

In [66]:
# Reshape the latest array to (3, 5, 1)
a.reshape(3,5,1)

array([[[0],
        [4],
        [4],
        [6],
        [8]],

       [[8],
        [2],
        [2],
        [2],
        [3]],

       [[7],
        [5],
        [7],
        [0],
        [7]]])

In [67]:
# Transpose the latest array
a.T

array([[0, 8, 7],
       [4, 2, 5],
       [4, 2, 7],
       [6, 2, 0],
       [8, 3, 7]])

What does the transpose do?

In [70]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
c = np.random.randint(0,10,(3,3))
d = np.random.randint(0,10,(3,2))
c

array([[2, 8, 3],
       [0, 3, 0],
       [4, 3, 7]])

In [71]:
d

array([[7, 6],
       [2, 0],
       [0, 2]])

In [69]:
# Perform a dot product on the two newest arrays you created
np.dot(c,d)

array([[13, 59],
       [18, 64],
       [16, 66]])

In [72]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
e = np.random.randint(0,10,(4,3))
f = np.random.randint(0,10,(4,3))

In [73]:
# Perform a dot product on the two newest arrays you created
np.dot(e,f)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
e.dot(f.T)

array([[47, 10, 60, 99],
       [36, 10, 49, 74],
       [37, 10, 57, 75],
       [16,  8, 16, 32]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [81]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
h = np.random.randint(0,10,(3,3))
i = np.random.randint(0,10,(3,3))


In [82]:
# Compare the two arrays with '>'
h > i

array([[False,  True, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [83]:
# Compare the two arrays with '>='
h >= i

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [85]:
# Find which elements of the first array are greater than 7
h > 7

array([[False, False, False],
       [ True, False,  True],
       [False, False, False]])

In [84]:
# Which parts of each array are equal? (try using '==')
h == i

array([[False, False, False],
       [ True, False,  True],
       [False, False, False]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(h)

array([[1, 5, 6],
       [1, 9, 9],
       [0, 0, 7]])

In [90]:
# Sort the indexes of one of the arrays you just created
np.argsort(h)

array([[2, 0, 1],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

In [91]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(h)

3

In [92]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(h)

6

In [98]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(h, axis=1)

array([1, 0, 1], dtype=int64)

In [99]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(h, axis=0)

array([2, 1, 2], dtype=int64)

In [102]:
# Create an array of normally distributed random numbers
np.random.randn(3,3)

array([[ 0.19534647, -0.5559449 , -0.12773483],
       [-1.56055707,  2.00034809, -1.20013174],
       [ 1.20138044,  0.14983372,  0.14090737]])

In [106]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.